# Generated by Django 4.2.3 on 2023-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
