# Generated by Django 4.2.3 on 2023-07-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='start_date',
        ),
    ]
