# Generated by Django 4.2.3 on 2023-07-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_date_post_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='end_date',
        ),
    ]
